#!/bin/bash

# Auto-merge script for Claude branches to MAIN-FUSION
# This script handles automatic merging with conflict detection

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
MAIN_FUSION_BRANCH="MAIN-FUSION"
CLAUDE_BRANCH="${1}"
REPO_OWNER="${2:-leon-madara}"
REPO_NAME="${3:-my-website}"

# Validate input
if [ -z "$CLAUDE_BRANCH" ]; then
    echo -e "${RED}Error: Branch name is required${NC}"
    echo "Usage: $0 <claude-branch-name> [repo-owner] [repo-name]"
    exit 1
fi

# Check if branch is a claude/* branch
if [[ ! "$CLAUDE_BRANCH" =~ ^claude/ ]]; then
    echo -e "${RED}Error: Branch must start with 'claude/'${NC}"
    exit 1
fi

echo -e "${GREEN}Starting auto-merge process...${NC}"
echo "Source branch: $CLAUDE_BRANCH"
echo "Target branch: $MAIN_FUSION_BRANCH"
echo ""

# Fetch latest changes
echo "Fetching latest changes..."
git fetch origin

# Check if MAIN-FUSION exists, create if not
if ! git rev-parse --verify "origin/$MAIN_FUSION_BRANCH" >/dev/null 2>&1; then
    echo -e "${YELLOW}MAIN-FUSION branch doesn't exist. Creating from main...${NC}"

    # Get the default branch (main or master)
    DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
    if [ -z "$DEFAULT_BRANCH" ]; then
        DEFAULT_BRANCH="main"
    fi

    git checkout -b "$MAIN_FUSION_BRANCH" "origin/$DEFAULT_BRANCH" || git checkout -b "$MAIN_FUSION_BRANCH"
    git push -u origin "$MAIN_FUSION_BRANCH"
else
    echo "Checking out MAIN-FUSION branch..."
    git checkout "$MAIN_FUSION_BRANCH"
    git pull origin "$MAIN_FUSION_BRANCH"
fi

# Get commit messages from the claude branch for PR description
echo "Generating change summary..."
COMMIT_LOG=$(git log --oneline "$MAIN_FUSION_BRANCH..origin/$CLAUDE_BRANCH" --pretty=format:"- %s (%h)" 2>/dev/null || echo "No commits found")
FILE_CHANGES=$(git diff --name-status "$MAIN_FUSION_BRANCH..origin/$CLAUDE_BRANCH" 2>/dev/null || echo "No changes")

# Try to merge
echo -e "${GREEN}Attempting merge...${NC}"
if git merge "origin/$CLAUDE_BRANCH" --no-ff -m "Auto-merge: $CLAUDE_BRANCH into $MAIN_FUSION_BRANCH"; then
    echo -e "${GREEN}✓ Merge successful!${NC}"

    # Push to MAIN-FUSION
    echo "Pushing to $MAIN_FUSION_BRANCH..."
    git push origin "$MAIN_FUSION_BRANCH"

    # Create a detailed PR description file for documentation
    PR_FILE="/tmp/pr-description-$(date +%s).md"
    cat > "$PR_FILE" <<EOF
# Auto-Merge: $CLAUDE_BRANCH → $MAIN_FUSION_BRANCH

## Summary
Automatically merged changes from Claude Code session.

**Branch:** \`$CLAUDE_BRANCH\`
**Target:** \`$MAIN_FUSION_BRANCH\`
**Date:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")

## Changes

### Commits
$COMMIT_LOG

### Files Modified
\`\`\`
$FILE_CHANGES
\`\`\`

## Status
✅ **Merged successfully** - No conflicts detected

---
*This merge was performed automatically by the MAIN-FUSION automation system.*
EOF

    echo -e "${GREEN}PR description saved to: $PR_FILE${NC}"
    cat "$PR_FILE"

    # Delete the claude branch
    echo -e "${YELLOW}Deleting $CLAUDE_BRANCH...${NC}"
    git push origin --delete "$CLAUDE_BRANCH" || echo "Branch already deleted or doesn't exist remotely"

    echo -e "${GREEN}✓ Auto-merge completed successfully!${NC}"
    exit 0

else
    # Merge failed - likely conflicts
    echo -e "${RED}✗ Merge failed - conflicts detected${NC}"

    # Abort the merge
    git merge --abort

    # Create conflict report
    CONFLICT_FILE="/tmp/conflict-report-$(date +%s).md"
    cat > "$CONFLICT_FILE" <<EOF
# ⚠️ Merge Conflict Detected

## Details
**Branch:** \`$CLAUDE_BRANCH\`
**Target:** \`$MAIN_FUSION_BRANCH\`
**Date:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")

## Action Required
Manual resolution needed. The branch \`$CLAUDE_BRANCH\` has been preserved for manual merging.

## Steps to Resolve

1. Checkout the MAIN-FUSION branch:
   \`\`\`bash
   git checkout $MAIN_FUSION_BRANCH
   git pull origin $MAIN_FUSION_BRANCH
   \`\`\`

2. Attempt the merge:
   \`\`\`bash
   git merge origin/$CLAUDE_BRANCH
   \`\`\`

3. Resolve conflicts in the affected files

4. Complete the merge:
   \`\`\`bash
   git add .
   git commit -m "Merge $CLAUDE_BRANCH into $MAIN_FUSION_BRANCH (manual resolution)"
   git push origin $MAIN_FUSION_BRANCH
   \`\`\`

5. Delete the claude branch when done:
   \`\`\`bash
   git push origin --delete $CLAUDE_BRANCH
   \`\`\`

## Commits in Branch
$COMMIT_LOG

## Files with Potential Conflicts
$FILE_CHANGES

---
*This conflict report was generated by the MAIN-FUSION automation system.*
EOF

    echo -e "${RED}Conflict report saved to: $CONFLICT_FILE${NC}"
    cat "$CONFLICT_FILE"

    echo -e "${YELLOW}Branch $CLAUDE_BRANCH has been preserved for manual resolution${NC}"
    exit 1
fi
